services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: sunat
      POSTGRES_PASSWORD: sunat
      POSTGRES_DB: sunat
    ports:
      - '5434:5432'
    volumes:
      - sunat-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U sunat']
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    command: ['redis-server', '--appendonly', 'yes']
    ports:
      - '6380:6379'
    volumes:
      - sunat-redisdata:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  sunat-pgdata:
  sunat-redisdata:
